### ISSUE TITLE
[Request] Add playerIsGM() function

### ISSUE THREAD

**Issue by LaytonGB** [Carl-Hugo/types-roll20#1]
```ts
/**
 * Returns true if the referenced player is a GM, else false.
 * @param playerID The ID of a player.
 */
declare function playerIsGM(playerID: string): boolean;
```

**Comment by Carl-Hugo** [comment]
If you open a PR, I'll merge it. 
Please also, bump the version number (minor or patch). 
I should have set a CI/CD pipeline somewhere that should deploy the new version automatically; if it does not, I'll see what I can do to make it happen (I don't really use Roll20 these days).

**Comment by LaytonGB** [comment]
I've since added a Macro object. Would you want me to throw that in the same pull request?

**Comment by Carl-Hugo** [comment]
No CD pipeline, I pushed it manually...
